### ISSUE TITLE
galleryCollectionView.centerCellIndexPath Always returns nil

### ISSUE THREAD

**Issue by havebeenfitz** [ro6lyo/UICollectionViewGallery#1]
Hi, and thanks for a library. I just have one problem with getting the indexPath for a centered cell. Maybe you could help with this? It always returns nil regarding of where it called from

**Comment by ro6lyo** [comment]
It working fine, one thing  to remember you have to get it when the scrollAnimation is over

<img width="698" alt="screen shot 2018-04-30 at 13 08 38" src="https://user-images.githubusercontent.com/13335070/39422815-a32d8b1e-4c77-11e8-9ed5-0b7a49aea62e.png">
